apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 80 # 외부에서 80포트로 접속 (HTTP 기본 포트)
      targetPort: 80 # 컨테이너의 80포트로 연결
  selector:
    app: frontend
  # [추가] 외부 인터넷에서 접속할 수 있도록 LoadBalancer 타입으로 지정하는 것이 좋습니다.
  type: LoadBalancer 